language:
  - swift
osx_image: xcode10.1
script:
  - xcodebuild: /Users/travis/build/bredmond5/Food-Reader/MyPricePal -scheme MyPricePal -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' build test
after_success:
  - bash <(curl -s https://codecov.io/bash) 
