os: osx
osx_image: xcode10.2
language: swift

script: xcodebuild clean build test -quiet -workspace MyPricePal/MyPricePal.xcworkspace -scheme "MyPricePal" -sdk iphonesimulator -destination "platform=iOS simulator,OS=12.2,name=iPhone X" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO 
