os: osx
osx_image: xcode10.2
language: swift

before_script:
  - docker build -t buildroot . > build.log 2>&1
  - while sleep 5m; do echo "=====[ $SECONDS seconds, buildroot still building... ]====="; done &
  - time docker run --rm -v $PWD/build:/build buildroot >> build.log 2>&1
  - kill %1

script: xcodebuild clean build test -workspace MyPricePal/MyPricePal.xcworkspace -scheme "MyPricePal" -sdk iphonesimulator -destination "platform=iOS simulator,OS=12.2,name=iPhone X" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO 
