osx_image: xcode9
language: swift

script:
- xcodebuild -scheme test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=12.1' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false

