# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'C++' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
#pod ‘Charts/Realm’
  # Pods for C++
pod 'SwiftCharts', '~> 0.6.1'

  target 'C++Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'C++UITests' do
    inherit! :search_paths
    # Pods for testing
	
  end

end
