# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
platform :ios, '9.0'

target 'TestingBarcode' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for TestingBarcode

pod 'BarcodeScanner'
pod 'SwiftLint'

end
